definitions:
  api.LoginResponse:
    properties:
      token:
        type: string
    type: object
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
info:
  contact:
    email: 252615299@qq.com
    name: ruomu
    url: blog.seeln.com
  title: ticket-crawler API
  version: "1.0"
paths:
  /login:
    post:
      description: 用户登录接口
      parameters:
      - description: 用户名
        in: query
        name: userName
        required: true
        type: string
      - description: 密码
        in: query
        name: passWord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  $ref: '#/definitions/api.LoginResponse'
              type: object
      summary: 登录
      tags:
      - user
  /signin:
    post:
      description: 用户注册接口
      parameters:
      - description: 用户名
        in: query
        name: userName
        required: true
        type: string
      - description: 密码
        in: query
        name: passWord
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  type: boolean
              type: object
      summary: 注册
      tags:
      - user
swagger: "2.0"
