basePath: /api/v1
definitions:
  api.LoginResponse:
    properties:
      token:
        type: string
    type: object
  app.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: 252615299@qq.com
    name: ruomu
    url: blog.seeln.com
  title: ticket-crawler API
  version: "1.0"
paths:
  /login:
    post:
      description: 用户登录接口
      parameters:
      - description: 用户名
        in: body
        name: userName
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: passWord
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  $ref: '#/definitions/api.LoginResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 登录
      tags:
      - user
  /signup:
    post:
      description: 用户注册接口
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: passWord
        required: true
        schema:
          type: string
      - description: 确认密码
        in: body
        name: rePassword
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  type: boolean
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 注册
      tags:
      - user
  /ticket:
    post:
      description: 通过这个接口，去第三方获取机票价格
      parameters:
      - description: 出发地
        in: body
        name: fromCity
        required: true
        schema:
          type: string
      - description: 目的地
        in: body
        name: toCity
        required: true
        schema:
          type: string
      - description: 开始日期
        in: body
        name: startDate
        required: true
        schema:
          type: string
      - description: 截止日期
        in: body
        name: endDate
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success Response
          schema:
            allOf:
            - $ref: '#/definitions/app.Response'
            - properties:
                data:
                  type: boolean
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: 获取机票价格源数据
      tags:
      - ticket
swagger: "2.0"
